wandb:
  run_name: Nexusflow/Athene-V2-Chat
api: vllm
num_gpus: 4
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: Nexusflow/Athene-V2-Chat #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: Nexusflow/Athene-V2-Chat
  size_category: 30Bâ‰¤
  size: 72706203648
  release_date: 11/15/2024
