wandb:
  run_name: "cohere/command-r-plus-08-2024" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthropic", "google", "cohere", "vllm", "mistral", "bedrock"
api: "cohere"
batch_size: 32 # vllmは256, apiは32を推奨
# inference_interval

generator:
  preamble: ""  # Put a custom preamble here if needed

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "command-r-plus-08-2024"  # put the name of Cohere model here
  size_category: "api"
  size: null
  release_date: "8/30/2024"