wandb:
  run_name: meta-llama/Meta-Llama-3-70B-Instruct
api: vllm
num_gpus: 2
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: meta-llama/Meta-Llama-3-70B-Instruct #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: meta-llama/Meta-Llama-3-70B-Instruct
  size_category: 30Bâ‰¤
  size: 70553706496
  release_date: 4/18/2024
  max_model_len: 2500
