wandb:
  run_name: openai/gpt-4-turbo-2024-04-09
api: openai
batch_size: 32
model:
  pretrained_model_name_or_path: gpt-4-turbo-2024-04-09 #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  size_category: api
  size: null
  release_date: 4/9/2024
