wandb:
  run_name: openai/gpt-4o-2024-05-13
api: openai
batch_size: 32
model:
  pretrained_model_name_or_path: gpt-4o-2024-05-13 #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  size_category: api
  size: null
  release_date: 5/13/2024
