wandb:
  run_name: Rakuten/RakutenAI-7B-chat
api: vllm
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: Rakuten/RakutenAI-7B-chat #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: Rakuten/RakutenAI-7B-chat
  size_category: <10B
  size: 7372804096
  release_date: 3/22/2024
