wandb:
  run_name: karakuri-ai/karakuri-lm-8x7b-instruct-v0.1
api: vllm
num_gpus: 2
batch_size: 256
model:
  use_wandb_artifacts: false
  max_model_len: 3500
  pretrained_model_name_or_path: karakuri-ai/karakuri-lm-8x7b-instruct-v0.1 #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: karakuri-ai/karakuri-lm-8x7b-instruct-v0.1
  size_category: 30Bâ‰¤
  size: 46703841280
  release_date: 6/24/2024
