wandb:
  run_name: "mistral/mistral-large" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthropic", "google", "cohere", "vllm", "mistral", "bedrock"
api: mistral
batch_size: 1 # vllmは256, apiは32を推奨

model:
  pretrained_model_name_or_path: "mistral-large" #if you use openai api, put the name of model
  size: "api"
  release_date: "2/26/2024"