wandb:
  run_name: "cyberagent/calm3-22b-chat" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "cyberagent/calm3-22b-chat" #if you use openai api, put the name of model
  chat_template: "cyberagent/calm3-22b-chat"
  size_category: "10B≤ <30B"
  size: 
  release_date: "7/2/2024"