wandb:
  run_name: "Qwen/Qwen3-14B:reasoning" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm-external
base_url: 'http://vllm:8000/v1'
num_gpus: 1
batch_size: 256 # vllmは256, apiは32を推奨
# inference_interval: 1 # seconds

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "Qwen/Qwen3-14B" #if you use openai api, put the name of model
  size_category: "10B≤ <30B"
  size: 1
  release_date: "4/28/2025"

vllm: # vLLM server-side launch configuration
  extra_args:
    - '--override_generation_config={"temperature":0.6,"top_p":0.95}' # do not include space
    - --reasoning-parser=qwen3

generator:
  temperature: 0.6
  top_p: 0.95
  extra_body:
    chat_template_kwargs:
      enable_thinking: true

jaster:
  override_max_tokens: 16384

jtruthfulqa:
  generator_config:
    max_tokens: 16384

swebench:
  max_tokens: 16384

mtbench:
  max_new_token: 16384
  temperature_override:
    writing: 0.6
    roleplay: 0.6
    extraction: 0.6
    math: 0.6
    coding: 0.6
    reasoning: 0.6
    stem: 0.6
    humanities: 0.6

hallulens:
  generator_config:
    max_tokens: 16384
    temperature: 0.6
    top_p: 0.95

hle:
  max_completion_tokens: 16384

arc_agi_2:
  max_output_tokens: 16384

testmode: true
run:
  jaster: true
  jmmlu_robustness: true # if this is set as true, jaster should set as true
  mtbench: true
  jbbq: false
  toxicity: true
  jtruthfulqa: true
  hle: true
  swebench: true
  bfcl: false
  hallulens: true
  arc_agi_2: true
  aggregate: false
