wandb:
  run_name: 01-ai/Yi-1.5-34B-Chat
api: vllm
num_gpus: 2
batch_size: 256
model:
  use_wandb_artifacts: false
  max_model_len: 3500
  pretrained_model_name_or_path: 01-ai/Yi-1.5-34B-Chat #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: 01-ai/Yi-1.5-34B-Chat
  size_category: 30Bâ‰¤
  size: 34388917248
  release_date: 5/13/2024
