wandb:
  run_name: "Rakuten/RakutenAI-7B-chat" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "Rakuten/RakutenAI-7B-chat" #if you use openai api, put the name of model
  chat_template: "Rakuten/RakutenAI-7B-chat"
  size: "10B<"
  release_date: "3/22/2024"

