wandb:
  run_name: microsoft/Phi-4-mini-instruct
api: vllm
batch_size: 256
model:
  use_wandb_artifacts: false
  max_model_len: 3500
  pretrained_model_name_or_path: microsoft/Phi-4-mini-instruct #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: microsoft/Phi-4-mini-instruct
  size_category: <10B
  size: 384000000000
  release_date: 6/11/2025
