wandb:
  run_name: "Qwen/Qwen2.5-72B-Instruct" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm
num_gpus: 4
batch_size: 256 # vllmは256, apiは32を推奨
gpu_memory_utilization: 0.9

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "Qwen/Qwen2.5-72B-Instruct" #if you use openai api, put the name of model
  chat_template: "Qwen/Qwen2.5-72B-Instruct"
  size_category: "30B≤"
  size: 72706203648
  release_date: "9/19/2024"