wandb:
  run_name: tokyotech-llm/Llama-3-Swallow-8B-Instruct-v0.1
api: vllm
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: tokyotech-llm/Llama-3-Swallow-8B-Instruct-v0.1 #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: tokyotech-llm/Llama-3-Swallow-8B-Instruct-v0.1
  size_category: <10B
  size: 8030261248
  release_date: 7/1/2024
