wandb:
  run_name: grok-beta
api: xai
batch_size: 32
model:
  pretrained_model_name_or_path: grok-beta #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  size_category: api
  size: null
  release_date: 10/21/2024
