wandb:
  run_name: Qwen/Qwen2-1.5B-Instruct
api: vllm
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: Qwen/Qwen2-1.5B-Instruct #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: Qwen/Qwen2-1.5B-Instruct
  size_category: <10B
  size: 1543714304
  release_date: 3/28/2024
