wandb:
  run_name: "openai/gpt-4-0613" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: openai
batch_size: 32 # vllmは256, apiは32を推奨

model:
  pretrained_model_name_or_path: "gpt-4-0613" #if you use openai api, put the name of model
  size_category: "api"
  size: null
  release_date: "6/13/2023"

