wandb:
  run_name: cyberagent/calm2-7b-chat
api: vllm
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: cyberagent/calm2-7b-chat #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: cyberagent/calm2-7b-chat
  size_category: <10B
  size: 7008948224
  release_date: 5/17/2023
