wandb:
  run_name: anthropic.claude-3-5-sonnet-20240620-v1:0
api: amazon_bedrock
batch_size: 1
inference_interval: 10
model:
  pretrained_model_name_or_path: anthropic.claude-3-5-sonnet-20240620-v1:0 #if you use openai api, put the name of model
  bfcl_model_name: "claude-3-5-sonnet-20240620-FC" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  size_category: api
  size: null
  release_date: 6/20/2024
