wandb:
  log: True
  entity: "wandb-japan"
  project: "llm-leaderboard3"
  run_name: "cyberagent/calm2-7b-chat" # use run_name defined above

github_version: v2.0.0 #for recording

testmode: true

# GLP（基礎的言語能力）とALT（アライメント能力）のそれぞれで評価を行うための設定（Trueで評価を行う）
run:
  GLP: true
  ALT: true

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "upstage", "vllm"
api: vllm
batch_size: 256 # vllmは256, apiは32を推奨

model:
  use_wandb_artifacts: false
  artifacts_path: ""
  pretrained_model_name_or_path: "cyberagent/calm2-7b-chat" #if you use openai api, put the name of model
  chat_template: "cyberagent/calm2-7b-chat"
  dtype: 'float16'
  max_model_len: 4096
  trust_remote_code: true
  device_map: "auto"
  load_in_8bit: false
  load_in_4bit: false

generator:
  top_p: 1.0
  # top_k: 0
  temperature: 0.1
  # repetition_penalty: 1.0
  max_tokens: 128

num_few_shots: 4

jaster:
  message_intro: "以下に、あるタスクを説明する指示があり、それに付随する入力が更なる文脈を提供しています。リクエストを適切に完了するための回答を記述してください。"
  artifacts_path: "wandb-japan/llm-leaderboard-test/jaster:v2"
  dataset_dir: "jaster/evaluation"

jmmlu_robustness: True

lctg:
  artifacts_path: "wandb-japan/llm-leaderboard3/lctg:v0"
  dataset_dir: "lctg"

bbq:
  aaa: aaa

sample_dataset:
  artifacts_path: 't-ibi/llm-leaderboard/sample_dataset:v1'
  dataset_dir: 'sample_dataset'
  language: ja

#jbbq:

toxicity:
  artifact_path: 'wandb-japan/toxicity-dataset-private/toxicity_dataset_subset:v1'
  judge_prompts_path: 'wandb-japan/toxicity-dataset-private/toxicity_judge_prompts:v1'
  max_workers: 5
  judge_model: 'gpt-4o-2024-05-13'
  visualize_ids: '[0, 1]'

mtbench:
  temperature_override:
    writing: 0.7
    roleplay: 0.7
    extraction: 0.0
    math: 0.0
    coding: 0.0
    reasoning: 0.0
    stem: 0.1
    humanities": 0.1
  question_artifacts_path: 'wandb-japan/llm-leaderboard/mtbench_ja_question:v0' # if testmode is true, small dataset will be used
  question_artifacts_path_test: 'wandb-japan/llm-leaderboard/mtbench_ja_question_small_for_test:v0'
  referenceanswer_artifacts_path: 'wandb-japan/llm-leaderboard/mtbench_ja_referenceanswer:v0' # if testmode is true, small dataset will be used
  referenceanswer_artifacts_path_test: 'wandb-japan/llm-leaderboard/mtbench_ja_referenceanswer_small_for_test:v0'
  judge_prompt_artifacts_path: 'wandb-japan/llm-leaderboard/mtbench_ja_prompt:v1' 
  bench_name: 'japanese_mt_bench'
  model_id: null # cannot use '<', '>', ':', '"', '/', '\\', '|', '?', '*', '.'
  question_begin: null 
  question_end: null 
  max_new_token: 1024
  num_choices: 1
  num_gpus_per_model: 1
  num_gpus_total: 1
  max_gpu_memory: null
  dtype: bfloat16 # None or float32 or float16 or bfloat16
  # for gen_judgment
  judge_model: 'gpt-4o-2024-05-13'
  mode: 'single'
  baseline_model: null 
  parallel: 1
  first_n: null

